### ISSUE TITLE
Known-unknown split returns false splits with only 1 rating per user

### ISSUE THREAD

**Issue by philippschmalen** [mhahsler/recommenderlab#31] opened 2019-04-19 08:13 UTC
The binaryRatingMatrix I'm working with contains several rows with just 1 rating per user. I developed a custom UBCF that takes users' metadata to still be able to predict, even with 0 given ratings. When testing the method with given all-but-one ratings, I noticed a bug within .splitKnownUnknown() (called by evaluationScheme) that assigns nothing to the unknown split. 
With given all-but-one there should be at least 1 rating per row.

Here is a reproducible example:
```R
set.seed(2100)
#parameters of constructed binaryRatingMatrix
nr_users <- 400 
nr_items <- 500 
sparsity <- 0.004 

#create random binaryRatingMatrix
data <- new("binaryRatingMatrix",
  data=as(t(as(Matrix(rbinom(nr_users*nr_items , 1 , sparsity), 
          nrow=nr_users, ncol=nr_items, sparse = TRUE),
         "ngCMatrix")), "itemMatrix"))
#select rows with min. 1 rating/user
min_1_item <- data[rowCounts(data) >= 1] 

  #inspect nr of ratings/user
  table(rowCounts(min_1_item))
  1   2   3   4   5   6   7   8 
120  88  74  47  12   3   1   1 

#Evaluation scheme with given-protocol all-but-one
es <- evaluationScheme(min_1_item, method='split', train=0.8, given=-1)
train_set <- getData(es, type='train')
known <- getData(es, type='known')
unknown <- getData(es, type='unknown')
unknown #should have at least as many ratings as rows

70 x 500 rating matrix of class ‘binaryRatingMatrix’ with 49 ratings.
#too few ratings 
####
```

The problem lies in the sample() function, which returns "integer(0)" when there is nothing to sample from. For a user with 1 rating, there are 0 given/known entries and 1 outcome/unknown entries.
Below you find my workaround within splitKnownUnknown(). Feel free to use it for the fix:
```R
setMethod(".splitKnownUnknown_fixed", signature(data="binaryRatingMatrix"), 
  function(data, given) {

    ## given might of length one or length(data)
    if(length(given)==1) given <- rep(given, nrow(data))
    nitems <- rowCounts(data)

    allBut <- given < 0
    if(any(allBut)) {
      given[allBut] <- nitems[allBut] + given[allBut]
    }

    if(any(given>nitems)) stop("Not enough ratings for user" ,
      paste(which(given>nitems), collapse = ", "))

    l <- getList(data, decode=FALSE) #item labels of ratings

    known_index <- lapply(1:length(l), 
      FUN = function(i) { 
          if(given[i] == 0) 0 
          else sample(1:length(l[[i]]), given[i]) 
        }
      ) #FIXED: sample() returns integer(0) for row with 0 known/1 unknown 

    #added due to integer(0) problem
    unknown_index <- lapply(1:length(l), 
    FUN = function(i) {   
        if(given[i] == 0) 1   
        else -known_index[[i]]      
      }     
    )   

    #define KNOWN ratings    
    known <- encode(
      lapply(1:length(l), FUN = function(x)
        l[[x]][known_index[[x]]]),  
      itemLabels = itemLabels(data@data)
      )
    rownames(known) <- rownames(data)

    #define UNKNOWN ratings
    unknown <- encode(
      lapply(1:length(l), FUN = function(x)
        l[[x]][unknown_index[[x]]]), 
      itemLabels = itemLabels(data@data))
    rownames(unknown) <- rownames(data)

    known <- new("binaryRatingMatrix", data = known)
    unknown <- new("binaryRatingMatrix", data = unknown)

    list(
      known = known,
      unknown = unknown
    )
  })

```

**Comment by mhahsler** [comment] 2019-04-22 17:26
Thank you for the bug report. The bug is now fixed on GitHub. The code creates now also a warning since I think for most users this would indicate a mistake on their side. Please test the code and let me know if the fix works as intended.

**Closed by mhahsler** 2019-04-22 17:26 UTC
Labels: bug
